stages:
  - build
  - test
  - package
  - deploy

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 1 week