name: deployment-workflow
on: push

jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - run: mvn compile
      - name: Upload build stuff for job 1
        uses: actions/upload-artifact@v2
        with:
          name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
          path: "target/*"

  test:
    name: test
    runs-on: self-hosted
    needs: build
    steps:
      - run: mvn test

  package:
    name: package
    runs-on: self-hosted
    needs: build
    steps:
      - run: mvn package
      - name: Package Artifact from maven
        uses: actions/upload-artifact@v2
        with:
         name: $CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
         expire_in: 1 week
         path: "target/*.war"

  deploy_test:
    name: deploy_test
    runs-on: self-hosted
    needs: package
    environment:
      name: test
      url: http://localhost:8080/game2048
    steps:
      - run: docker rm --force tomcat
      - run: docker image rm --force game2048
      - run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
      - run: docker run --rm -d --name tomcat -p 8080:8080 game2048
